dekanat_3/dekanat_3/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('mainapp.urls', namespace='mainapp')),
    path('admin/', admin.site.urls),
]

dekanat_3/mainapp/urls.py
import mainapp.views as mainapp

from django.urls import path

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.index, name='index'),
    path('groups/', mainapp.group_list, name='group_list'),
    # path('group/student/<int:group_pk>/', mainapp.student_page, name='students_page'),
    # path('group/create/', mainapp.create_group, name='create_group')
]

dekanat_3/mainapp/models.py
from django.db import models


class Group(models.Model):
    name = models.CharField(max_length=128)
    desc = models.TextField(blank=True)

    def __str__(self):
        return self.name


class Student(models.Model):
    group = models.ForeignKey(Group,
                                 on_delete=models.CASCADE)
    name = models.TextField(max_length=128)

    class Meta:
        verbose_name = 'Студент'
        verbose_name_plural = 'Студенты'

dekanat_3/mainapp/forms.py
from django import forms

from mainapp.models import Group


class GroupForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = (
            'name',
            'desc',
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for name, item in self.fields.items():
            item.widget.attrs['class'] = 'form-control mt-1'
            item.widget.attrs['style'] = 'resize: none'

dekanat_3/mainapp/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse

from mainapp.models import Group, Student
from mainapp.forms import GroupForm


def index(request):
    context = {
        'page_title': 'Главная'
    }
    return render(request, 'mainapp/index.html', context)


def group_list(request):
    groups = Group.objects.all()
    context = {
        'groups': groups,
        'page_title': 'Группы'
    }
    return render(request, 'mainapp/groups.html', context)


def student_page(request, groups_pk):
    students = Student.objects.filter(groups_id=groups_pk)
    context = {
        'students': students,
        'page_title': 'Студенты'
    }
    return render(request, 'mainapp/student_page.html', context)


def create_group(request):
    if request.method == 'POST':
        form = GroupForm(request.POST)
        if form.is_valid():
            # form.save()
            return HttpResponseRedirect(reverse('mainapp:groups'))
    else:
        form = GroupForm()
    context = {
        'title': 'Добавить группу',
        'form': form,
    }
    return render(request, 'mainapp/group_add.html', context)

dekanat_3/mainapp/templates/mainapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Группы</title>
</head>
<body>
<div class="menu">
    <ul>
        <li>
            <a href="{% url 'mainapp:index' %}">Главная</a>
        </li>
        <li>
            <a href="{% url 'mainapp:group_list' %}">Группы</a>
        </li>
    </ul>
    {% block content %}
    {% endblock %}
</div>
</body>
</html>

dekanat_3/mainapp/templates/mainapp/group.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

dekanat_3/mainapp/templates/mainapp/group_add.html
{% extends 'mainapp/base.html' %}
{% block content %}
    <div>
        <form method="post">
 {% csrf_token %}
 {{ form.as_p }}
            <button>"Добавить группу</button>
        </form>
    </div>
{% endblock %}

dekanat_3/mainapp/templates/mainapp/groups.html
{% extends 'mainapp/base.html' %}
{% block content %}
<h1>Группы</h1>
<div>
    <ul>
        <li>
            <a href="{% url 'mainapp:create_group' %}">Создать группу</a>
        </li>
        {% for item in groups %}
<!--        <li>-->
<!--            <a href="{% url 'mainapp:groups' item.pk %}">-->
                {{ item }}
<!--            </a>-->
<!--        </li>-->
        {% endfor %}
    </ul>
</div>
{% endblock %}

dekanat_3/mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% block content %}

{% endblock %}

dekanat_3/mainapp/templates/mainapp/student_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>